# Introduction



## magic command in IPython and Jupyter Notebook
1. %pwd
2. ? ?? **?
3. %paste %cpaste
4. %run %load - 将其他脚本独立执行在当前环境中，但是能够访问其中的变量和计算结果

In [1]:
%pwd

'/Users/collinsliu/jupyter/python_learning_basics'

In [2]:
path = '/Users/collinsliu/jupyter/python_learning_basics/python_for_data_analysis_01.ipynb'
open(path).readline()

'{\n'

In [3]:
import sys

print(sys.argv)

['/Users/collinsliu/opt/anaconda3/lib/python3.9/site-packages/ipykernel_launcher.py', '-f', '/Users/collinsliu/Library/Jupyter/runtime/kernel-1cce7e54-f2d1-4678-8740-141e606afb0d.json']


### time timeit
1. time 计算一次运行的时间
2. timeit 计算多次运行后的平均值

In [4]:
import numpy as np

a = np.random.randn(100,100)
%timeit np.dot(a,a)

120 µs ± 33.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [5]:
%time np.dot(a,a)

CPU times: user 1.24 ms, sys: 605 µs, total: 1.85 ms
Wall time: 328 µs


array([[  1.50037706,  22.49623362, -12.12656798, ...,   1.72503629,
         -5.24800675, -11.83171313],
       [-11.38453896,   9.855974  ,   5.97792139, ...,  -4.89087597,
         -2.01550345, -10.62897141],
       [ -7.92667631,   8.35180731,  11.06144292, ...,  -7.81310707,
         -5.49945916,  -1.7164878 ],
       ...,
       [ -1.25936348,  -9.7170556 , -18.96496902, ...,  -4.59154916,
          4.18318841,  -6.05732026],
       [ -6.83046293,   2.762347  ,  19.25781217, ...,  11.07428804,
         -9.05828889,   0.78988761],
       [  9.82414804,  -6.4448292 ,   0.87163114, ..., -10.98951163,
        -17.29293344, -16.65044285]])

### who who_ls whos


In [6]:
%who_ls a

[]

### matplotlib | matplotlib inline

In [9]:
import matplotlib
from matplotlib import pyplot as plt

%matplotlib inline

## python basic grammars

### object basics
1. built-in function

In [10]:
# decide whether the object is of one kind - isinstance
instance_a = 5
print(isinstance(instance_a, int))
print("######")
instance_b = "name"
instance_c = 5.5
print(isinstance(instance_b,str))
print(isinstance(instance_c,(int, float)))

True
######
True
True


In [11]:
# decide whether the object has __iter__ function - which means it's iterrable
instance_d = "a string"
isiterable(instance_d)

NameError: name 'isiterable' is not defined

### formatting print

In [15]:
# print formatted results
print("{:.2f} is float".format(instance_c))

5.50 is float


### time in python
1. datetime package
2. two important function - **strftime** | **strptime**
3. **strftime** 从已有的datetim对象转换为格式输出
4. **strptime** 重新构造一个datetime对象并转换为格式输出

In [23]:
from datetime import date, time, datetime

dt = datetime(2022,11,9,19,46,50)
print(dt.hour)
print(dt.strftime("%Y-%m-%d %h:%m:%s"))
print(datetime.strptime("20221109","%Y-%m-%d"))

19
2022-11-09 Nov:11:1667994410


ValueError: time data '20221109' does not match format '%Y-%m-%d'

## innter structure

### immutable data structure - tuple
1. tuple() - 将其他格式转换为tuple格式

In [24]:
# tuple unpacking
exp_list = [(1,2,3), (4,5,6), (7,8,9)]
for a,b,c in exp_list:
    print("a={0}, b={1}, c={2}".format(a,b,c))

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [25]:
# tuple discarding
exp_tup = 1,2,3,4,5,6,7
print(exp_tup)
a,b,*rest = exp_tup
rest

(1, 2, 3, 4, 5, 6, 7)


[3, 4, 5, 6, 7]

In [27]:
# tuple common method - built-in methods for tuple
exp_tup2 = 1,2,3,4,54,3,3,3,3,3,3
exp_tup2.count(3)

7

### mutable. data structure - list
1. list() - 将其他格式转换为list格式
2. list经常用来实例化iterator或者是generator对象，直接使用**list()**函数即可
3. list的内置函数： append(item), insert(pos,item), pop(pos), remove(item), extend(list) 时间上比“+”更加节省
4. 判断元素是否在list中： 语法糖： in | not in - 但是是线性遍历，时间比dict或者是set要长很多
5. list的高级函数： sort() - 直接在原list的基础上进行排序


In [28]:
# list could be modified in-place
exp_list = [1, 3, 5, 3.6, "foo", [3,5]]
exp_list

[1, 3, 5, 3.6, 'foo', [3, 5]]

In [29]:
exp_list[1] = "this is changed"
exp_list

[1, 'this is changed', 5, 3.6, 'foo', [3, 5]]

#### sort: in-place function
1. has two parameters: key and reverse
2. key 输入一个fun,这个函数的输入值就是list中的各个元素，返回值是需要排序的对象

In [33]:
def sort_fun(lst):
    '''
    sort by second element in one input list
    '''
    return lst[1]

exp_list1 = [[3,5],[6,17],[2,23],[7,0],[12,3],[42,41],[45,33],[87,100]]
print(exp_list1, type(exp_list1))
exp_list1.sort(key=sort_fun)
print(exp_list1, type(exp_list1))

[[3, 5], [6, 17], [2, 23], [7, 0], [12, 3], [42, 41], [45, 33], [87, 100]] <class 'list'>
[[7, 0], [12, 3], [3, 5], [6, 17], [2, 23], [45, 33], [42, 41], [87, 100]] <class 'list'>


#### bisect module
1. 是一个模块，使用二分法像一个list中插入数据
2. 其中的bisect方法是找到应该插入的位置
3. 其中的insort方法是将该值插入到相应的位置上

In [37]:
import bisect

bisect_list = [13,23,6,4,3,60,7,15,34,52,5,0,12]
bisect_list.sort()
res = bisect.bisect(bisect_list,8)
print(res)
bisect.insort(bisect_list,8)
bisect_list


6


[0, 3, 4, 5, 6, 7, 8, 12, 13, 15, 23, 34, 52, 60]

#### slicing
1. 先开始的节点start是包含在区间中的，但是结束的节点end是不包含在区间中的 - 无论是从头到尾还是从尾到头都是一样
2. 比如[:3]是0，1，2；[-6:-2]是-5，-4，-3，-2
3. 无论是从前往后数还是从后往前数，开始的值都是0

### built-in sequencing function
1. enumerate
2. sorted
3. zip
4. reversed

#### enumerate - application: transfer list into dict

In [38]:
# transfer list into dict
exp_dict = {}
exp_list = ["foo",'bar','tar','war','mar']
for i,v in enumerate(exp_list):
    exp_dict[v] = i
exp_dict

{'foo': 0, 'bar': 1, 'tar': 2, 'war': 3, 'mar': 4}

#### sorted - just like list built-in function sort()

#### zip - packing differenct structures into one tuple
1. 如果多个结构进行zip操作，最后结果长度将取决于最短的结构，多余的部分会被丢弃
2. zip同时可以与\* \*\* 同时使用达到unzip的效果
3. zip的输出将会是一个zip对象，需要使用list()方法将这个对象实例化


In [43]:
# zip common usage example
exp_seq1 = ("foo","bar","tar","war")
exp_seq2 = ("A","B","C","D")
exp_dict2 = {}
for i,v in enumerate(zip(exp_seq1, exp_seq2)):
    exp_dict2[i] = v
print(exp_dict2)
print(zip(exp_seq1,exp_seq2))
print(list(zip(exp_seq1,exp_seq2)))

{0: ('foo', 'A'), 1: ('bar', 'B'), 2: ('tar', 'C'), 3: ('war', 'D')}
<class 'zip'>
[('foo', 'A'), ('bar', 'B'), ('tar', 'C'), ('war', 'D')]


In [45]:
# zip used for unzip
# zip here just combine together all first names and last names
coach = [("Charlie","Brown"),
         ("Lucy","Amuderson"),
         ("Lisa","Mocca"),
         ("Peppermint","Party"),
         ("Marcy","Green")]
first_name, last_name = zip(*coach)
first_name

('Charlie', 'Lucy', 'Lisa', 'Peppermint', 'Marcy')

#### reversed - reverse structure

### mutable data structure - dict
1. update()直接把新的dict插入到原本的dict中；
2. del key关键字或者是pop(key)能够删除相关的记录
3. get(key,default_value能够按条件返回一个相关记录
4. keys()以及values()能够返回dict所有的key或者是value值；但是需要通过list()实例化
5. 创建一个dict：实际上就是两个tuple进行zip操作
6. 向dict中插入对象：如果是分拣的方式，那么可以使用setdefault(key,default_key).append(value)
7. 或者使用collections中的defaultdict数据结构，直接定义如果不存在改key那么创建什么数据类型来承载这个key中的值

In [47]:
# create a dict from tuple
exp_dict3 = dict(zip(range(5),reversed(range(5,10))))
exp_dict3

{0: 9, 1: 8, 2: 7, 3: 6, 4: 5}

In [49]:
# insert new value into dict
from collections import defaultdict

words = {"apple","apricot","banana","banjiu","citrus","camellia","brown tea"}
by_letter = defaultdict(list)
for word in words:
    by_letter[word[0]].append(word)
by_letter

defaultdict(list,
            {'c': ['camellia', 'citrus'],
             'a': ['apple', 'apricot'],
             'b': ['banana', 'banjiu', 'brown tea']})

#### key selection
只有能够哈希化的数据结构能够作为key值，那么mutable的数据结构是不能够作为key值进行存储的，比如list,set,dict

### mutable data structure - set
1. {} 
2. 类似于list，但是其中的数据是不可以重复的，可以用来去重

### list | set | dict comprehension
1. 推断中可以使用map()函数
2. list的推断是能够使用到lambda函数的
3. 三种数据结构的推断是差不多的，但是list用来筛选或者是map，set用来分拣或者去重

In [51]:
# list comprehension
strings = ["apply", 'comply', 'imply', 'dupply', 'ply', 'fly', 'ly']
res_strings = [x.upper() for x in strings if len(x) >=2 and len(x) < 6]
res_strings

['APPLY', 'IMPLY', 'PLY', 'FLY', 'LY']

In [55]:
# set comprehension
res_length = {len(x) for x in strings} #本质上就是一个map函数
res_length2 = set(map(len, strings))

print(res_length)
res_length2

{2, 3, 5, 6}


{2, 3, 5, 6}

In [57]:
# dict comprehension
res_dict = {idx: val for idx,val in enumerate(strings)}
res_dict

{0: 'apply', 1: 'comply', 2: 'imply', 3: 'dupply', 4: 'ply', 5: 'fly', 6: 'ly'}

In [64]:
# nested list|tup comprehension
nested_list = [["Mary","Tom","David","Thomas"],
               ["Tim","Tong","Jake","Lucy"]]
# flatten the list
flatten_list = [name for names in nested_list for name in names if "T" not in name]
flatten_list

['Mary', 'David', 'Jake', 'Lucy']

In [68]:
# transfer list to tuple
res_tuple = [(tuple(name for name in names)) for names in nested_list]
res_tuple

[('Mary', 'Tom', 'David', 'Thomas'), ('Tim', 'Tong', 'Jake', 'Lucy')]

## namspaces scope and local functions
1. 作用域的四个范围
    1. local
    2. enclosing 嵌套函数中外部函数的变量，可以使用 nonlocal在内部函数中进行调用
    3. global 全局变量
    4. built-in python解释器使用的变量
   

In [72]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  '# decide whether the object is of one kind - isinstance\ninstance_a = 5\nprint(isinstance(instance_a, int))\nprint("######")\ninstance_b = "name"\ninstance_c = 5.5\nprint(isinstance(instance_b,instance_c,(str,float))',
  '# decide whether the object is of one kind - isinstance\ninstance_a = 5\nprint(isinstance(instance_a, int))\nprint("######")\ninstance_b = "name"\ninstance_c = 5.5\nprint(isinstance(instance_b,instance_c,(str,float)))',
  '# decide whether the object is of one kind - isinstance\ninstance_a = 5\nprint(isinstance(instance_a, int))\nprint("######")\ninstance_b = "name"\ninstance_c = 5.5\nprint(isinstance((instance_b,instance_c),(str,float)))',
  '# decide whether the object is of one kind - isins

In [73]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  '# decide whether the object is of one kind - isinstance\ninstance_a = 5\nprint(isinstance(instance_a, int))\nprint("######")\ninstance_b = "name"\ninstance_c = 5.5\nprint(isinstance(instance_b,instance_c,(str,float))',
  '# decide whether the object is of one kind - isinstance\ninstance_a = 5\nprint(isinstance(instance_a, int))\nprint("######")\ninstance_b = "name"\ninstance_c = 5.5\nprint(isinstance(instance_b,instance_c,(str,float)))',
  '# decide whether the object is of one kind - isinstance\ninstance_a = 5\nprint(isinstance(instance_a, int))\nprint("######")\ninstance_b = "name"\ninstance_c = 5.5\nprint(isinstance((instance_b,instance_c),(str,float)))',
  '# decide whether the object is of one kind - isins

### namespace

## functions
1. the returns of a function is default tuple
2. return of a function could also be set to dictionary
3. function  coulc be treated as obejcts
4. anonymous function - lambda function

In [75]:
def func():
    a = 10
    b = 20
    c = 30
    return {"a": a, "b":b, "c":c}
func()

{'a': 10, 'b': 20, 'c': 30}

In [87]:
import re

# function would be treated as object, which could be passed in tuples
cities = ["Beijing","Nan?jing","Shang##Hai","LANZHOU","g uang z hou","CHon!gQ!@#ing"]

def remove_punctuation(value):
    return re.sub("[?#!@]","",value)


partial_res_city = map(remove_punctuation, cities)
list(partial_res_city)

['Beijing', 'Nanjing', 'ShangHai', 'LANZHOU', 'g uang z hou', 'CHongQing']

In [92]:
functions = [str.strip, remove_punctuation, str.title]

def clean_string(strings, ops):
    res = []
    for string in strings:
        for function in ops:
            string = function(string)
        res.append(string)
    return res

res_city = clean_string(cities,functions)
res_city

['Beijing', 'Nanjing', 'Shanghai', 'Lanzhou', 'G Uang Z Hou', 'Chongqing']

#### lambda function - another way for function simplification

In [97]:
import math

# suppose for a simple apply function
def apply_to_list(obj, f):
    return [f(x) for x in obj]

some_list = [1,3,5,2,6,4,12]
res = apply_to_list(some_list, lambda x : int(math.pow(x,2)))
res

[1, 9, 25, 4, 36, 16, 144]

In [102]:
# also lambda function could be used for sort
some_strings = ["foo", "barbarbar", "cartar", "banana", "boycat", "aaaa", "aaabbaadddd"]
res = sorted(some_strings, key=lambda x: len(set(list(x))) )
res

['aaaa', 'foo', 'barbarbar', 'banana', 'aaabbaadddd', 'cartar', 'boycat']

#### Currying - one method for partial function

In [105]:
from functools import partial

def apply_add(x,y):
    return x + y

apply_add_five = partial(apply_add, 5)
res = apply_add_five(4)
res

9

### iterator
1. iter() function will generate one iterator 

In [108]:
one_exp_list = [1.4, 3.0, 5.7, 12.23, 6.01]
iter(one_exp_list)

#### itertools - built-in func package designed for iterable objects
1. combinations(iterable, k)
2. permutations(iterable, k)
3. groupby(iterable, keyfunc)
4. product(\*iterables, repeat=1)

In [113]:
import itertools

some_names = ["Amy", "Charlie", "Candy", "Mark", "Mosses", "Ezikel", "Emma", "David", "Dunky", "Dunken"]
for idx, val in itertools.groupby(some_names, lambda x: x[0]):
    print(idx,list(val))


A ['Amy']
C ['Charlie', 'Candy']
M ['Mark', 'Mosses']
E ['Ezikel', 'Emma']
D ['David', 'Dunky', 'Dunken']


# numpy - import numpy as np

## built-in functions and properties
1. ndim dtype shape 
2. function: full, full_like, eye, identity, zeros_like, ones_like, array|asarray, arange
3. astype() 
4. one note: all operations of slicing take place on the original ndarray, otherwise a **copy()** function is needed
5. <font color=red>for 3d array(most common), the order for slicing should be **height-row-column**</font>
6. boolean function applied on numpy array will always return a boolean array the same structure of the original ndarray; **make sure that all boolean arithmatic operations only have one symbol, that is | & !**

In [117]:
import numpy as np

some_arr = np.linspace(5,10,24).reshape(3,2,4)
print(some_arr[0,1,2])
some_arr

6.304347826086957


array([[[ 5.        ,  5.2173913 ,  5.43478261,  5.65217391],
        [ 5.86956522,  6.08695652,  6.30434783,  6.52173913]],

       [[ 6.73913043,  6.95652174,  7.17391304,  7.39130435],
        [ 7.60869565,  7.82608696,  8.04347826,  8.26086957]],

       [[ 8.47826087,  8.69565217,  8.91304348,  9.13043478],
        [ 9.34782609,  9.56521739,  9.7826087 , 10.        ]]])

### booolean function

In [130]:
names = np.array(["Bob", "Lucy", "Mary", "Bob", "Thomas", "Will", "Mary"])
values = np.random.randn(7,6)
print(values)

[[ 0.01379675  1.26788776 -0.10144308 -1.94386531  0.10892521  0.64140899]
 [ 0.39238022 -0.60525769  0.30474783 -0.01709643  0.47631887 -2.14930589]
 [-0.17004812 -0.42554714 -0.20412542 -0.82259763 -0.4300066  -1.12688866]
 [-0.24979829 -0.12506382  0.5875104   1.3267701   0.91762253 -1.3391061 ]
 [ 0.96514331  2.25468126  0.58462851  1.44611972 -0.74452604 -0.67770117]
 [-0.51675793  1.00320723  0.04805853  1.08730085  0.9186774   1.76182643]
 [ 1.12399156 -1.399       1.28184586 -0.88414047 -0.33409872 -0.36424341]]


In [132]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False, False,  True, False,  True, False])

### scalar operation
1. just applied to all elements in ndarray
2. change in values will always replace the original value
3. data slicing including **column-based slicing** and **boolean function slicing**
4. <font color=red>all boolean function will always return one boolean array</font>

In [135]:
import numpy as np

arr = np.random.randn(4,5)
print(arr)
arr[arr>0.5] = 0
print(arr)

[[ 0.43294344 -0.55423116 -0.15564094  0.61531015  0.04607718]
 [ 0.33427187  0.81298562  1.42346451 -0.39177768 -0.18494286]
 [ 1.11136169 -0.74552395  1.79718555 -0.99087628 -0.94369027]
 [ 0.26862531 -0.41797091  0.20812654  0.76546257  0.1641475 ]]
[[ 0.43294344 -0.55423116 -0.15564094  0.          0.04607718]
 [ 0.33427187  0.          0.         -0.39177768 -0.18494286]
 [ 0.         -0.74552395  0.         -0.99087628 -0.94369027]
 [ 0.26862531 -0.41797091  0.20812654  0.          0.1641475 ]]
